version: "3.5"
services:
  selenium:
    hostname: selenium
    image: selenium/standalone-chrome-debug:3.8.1
    extra_hosts:
      - ${TRAEFIK_SUBDOMAIN:-app}.${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}
    networks:
      - warden
      - default
